from pathlib import Path
import datetime, hashlib, json
R=Path(__file__).resolve().parent.parent
repo=R.parent.parent
package_path=Path(r'E:\ESTUDO APK\work\station-multiplayer-r77-20261008\package-01\evidence\package.json')
p=json.loads(package_path.read_text('utf8'))
assert p['allPackageEntriesVerified'] and not p['installed'] and not p['deployed']
(R/'evidence/package.json').write_bytes(package_path.read_bytes())
b=json.loads((R/'evidence/java-dex-build.json').read_text('utf8'))
status=dict(version='R77',state='compiled-signed-candidate-not-installed',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseAppCommit='a81c7fde61c6d048b4cea4c746052bd7304e600e',serverReturnCommit='bee3dcd5c2c0c0a228805957fe89b9a6023e8402',serverCandidateBase='ab192bf1585e30f303d041f13b36a1f9c96d2caa',apkSHA256=p['sha256'],apkBytes=p['bytes'],apkLocalPath=p['apk'],certificateSHA256=p['certificateSHA256'],sourceCount=b['sourceCount'],changedSourceCount=len(b['changedSources']),preservedSourceCount=b['preservedSources'],sourceManifestSHA256=b['overlayManifestSHA256'],clientDexSHA256=b['clientDexSHA256'],roomsDexSHA256=b['roomsDexSHA256'],runtimeSHA256=p['payloadHashes']['lib/arm64-v8a/libstation_retroarch.so'],snesCoreSHA256=p['payloadHashes']['lib/arm64-v8a/libstation_bsnes.so'],carouselSHA256=p['payloadHashes']['lib/arm64-v8a/libturbo_carousel.so'],packageEntriesPreserved=p['preservedEntries'],videosPreserved=p['totalVideos'],installed=False,serverDeployed=False,androidGameplayTested=False,physical3Or4PlayerTested=False,existingInstalledVersion='R76',catalogIds=2467,visibleCatalogIds=2212,metadataEditionCandidates=1454,metadataUnmatched=734,metadataMismatched=279,approvedMultiplayerProfiles=0,reviewedDisplayEntries=0,allGameFactsComplete=False,pending=['Operator review, profile/content binding and coordinated v3 activation','Exact game/mode/controller qualification on Android with 2, 3 and 4 devices','Catalogue remaining factual evidence, synopsis and rating gaps','v3 room invitation/code feature is not implemented; room-list join only'])
(R/'STATUS.json').write_text(json.dumps(status,ensure_ascii=False,indent=2)+'\n','utf8',newline='\n')
section=f'''## Recibo final da candidata\n\nAPK compilado e assinado: **`{p['sha256']}`**, {p['bytes']:,} bytes. Local: `{p['apk']}`. Certificado original preservado. Não instalada; nenhum servidor Linux alterado.\n\nJava: {b['sourceCount']} fontes ({len(b['changedSources'])} novas/alteradas, {b['preservedSources']} preservadas). DEX28 `{b['clientDexSHA256']}`; DEX35 `{b['roomsDexSHA256']}`. Foram alteradas exatamente seis entradas do APK e acrescentado apenas `assets/station-catalog/player-evidence-v1.json`; {p['preservedEntries']:,} entradas e os 59 vídeos permaneceram idênticos. O asset de contagens revisadas permanece vazio: a implementação está pronta para receber vínculos comprovados, mas a pesquisa não foi promovida em massa a fato.\n\n| Verificação local | Resultado |\n|---|---:|\n| Contrato/perfis/coordenador Java | 1.612 |\n| Concorrência do túnel | 148 |\n| Combinação de snapshots | 90 |\n| Saída humana vinculada à sala/geração | 227 |\n| Apresentação de jogadores | 188 |\n| Métodos de interface extraídos | 87 |\n| Evidência factual do carrossel | 175, mais 4.000 publicações concorrentes |\n| Runtime nativo | 758 e 12 guardas |\n| Mapeamento Multitap SNES | 6.609 |\n| Servidor C#/HTTPS-WSS/v2 | 253 + 152 + 91 |\n| Java ↔ C# HTTPS/WSS, 2/3/4 participantes | 9 sessões, 351 verificações, 25.560.000 bytes exatos |\n| Inventário / metadados pesquisados | 12.361 / 73.525 |\n\nA integração usa rede TLS local real e prontidão nativa simulada. Não executa jogos em Android nem mede latência de Internet. Consulte `tests/README.md`, `evidence/package.json`, `evidence/package-gates.json` e `STATUS.json`.\n\n'''
readme=R/'README.md';s=readme.read_text('utf8');assert '## Recibo final da candidata' not in s
readme.write_text(s.replace('## Pesquisa do catálogo\n',section+'## Pesquisa do catálogo\n'),'utf8',newline='\n')
handoff=R/'HANDOFF-APP-R77-PARA-SERVIDOR-20261008.md';h=handoff.read_text('utf8');handoff.write_text(h+'\n'+section,'utf8',newline='\n')
addition='''\n- `recipes/refine_presence_java.py` deve executar depois de `refine_information_ui.py`: registra a intenção humana de saída com sala, geração e protocolo, conserva falhas de rede e não sai de outra sala.\n- Ordem final das receitas de overlays: `implement_java.py` → `refine_java.py` → `refine_information_ui.py` → `refine_catalog_java.py` → `refine_presence_java.py`; então `freeze_sources.py`, `build_java.py`, `prepare_package_inputs.py` e `package_candidate.py`. Não regenerar fontes depois do freeze sem nova revisão/compilação.\n'''
s=readme.read_text('utf8').replace('## Limites\n',addition+'\n## Limites\n');readme.write_text(s,'utf8',newline='\n')
head=f'''# R77 candidata — salas de 2 a 4 e contagens por edição — 08/10/2026\n\nLeia `versions/station-multiplayer-r77-20261008/README.md`, `STATUS.json` e o handoff APP → SERVIDOR. APK `{p['sha256']}`, compilado/assinado, **não instalado e não homologado em três/quatro celulares**. Ambos aparelhos permanecem na R76. A produção declarada continua ab192bf; último retorno real bee3dcd. A candidata C# está isolada no snapshot, sem deploy e sem incorporação automática da 6f27.\n\nNovo protocolo station-stream.v3, runtime351cee4540e9 e core SNES0a3ac7b4fa5d exigem novos registros/perfis no servidor. Preservar os dez engines existentes. Perfis propostos approved:false, zero vínculos factuais promovidos; não habilitar por nome, maxusers ou similaridade. Catálogo:2.467 IDs,1.454 candidatos descritivos,734 sem correspondência,279 divergentes; não afirmar todas as fichas completas. Carrossel mostra — sem confirmação. Salas informam modo, capacidades exatas, ocupação e nomes/P1–P4 antes de aceitar/iniciar.\n\n209 fontes Java,24 novas/alteradas,185 preservadas; testes cruzados locais:9 sessões/351checks/25.560.000 bytes, sem gameplay Android. Seis entradas do APK alteradas,1 JSON novo,13.219 preservadas/59 vídeos. Controles/saves offline e certificado preservados. Convites/códigos v3 ainda não implementados; entrada pela lista de salas. Qualificar produção/perfis e testes físicos antes de substituir R76. Compilar E:, APK final G:, não publicar APK/ROM/BIOS/credenciais/dados pessoais.\n\n## Histórico anterior\n\n'''
a=repo/'AGENTS.md';a.write_text(head+a.read_text('utf8'),'utf8',newline='\n')
r=repo/'README.md';r.write_text(f'''# R77 candidata: salas de 2 a 4 jogadores\n\n[Implementação, pesquisa e limites](versions/station-multiplayer-r77-20261008/README.md) · [Handoff para o servidor](versions/station-multiplayer-r77-20261008/HANDOFF-APP-R77-PARA-SERVIDOR-20261008.md).\n\nAPK compilado/assinado, ainda não instalado. Ambos aparelhos permanecem na R76. Capacidade por jogo/modo, posições P1–P4 e textos antes da confirmação implementados. Registro v3, aprovação dos perfis e gameplay físico ainda pendentes. A pesquisa percorreu 2.467 IDs; não equivale a todas as informações factuais verificadas.\n\n## Histórico anterior\n\n'''+r.read_text('utf8'),'utf8',newline='\n')
print(json.dumps({'apkSHA256':p['sha256'],'documented':True,'installed':False}))