#include <jni.h>
#include <dlfcn.h>
#include <android/log.h>
JNIEXPORT jboolean JNICALL Java_org_emulationstation_frontend_VitaBootstrap_bindSdl(JNIEnv *env,jclass ignored){
 (void)ignored;static int ready;if(ready)return JNI_TRUE;
 void *lib=dlopen("libVita3K.so",RTLD_NOW|RTLD_LOCAL);if(!lib)return JNI_FALSE;
{ jclass c=(*env)->FindClass(env,"org/vtsdlx/app/HIDDeviceManager");if(!c)return JNI_FALSE;
JNINativeMethod methods[]={{"HIDDeviceRegisterCallback","()V",NULL},{"HIDDeviceReleaseCallback","()V",NULL},{"HIDDeviceConnected","(ILjava/lang/String;IILjava/lang/String;ILjava/lang/String;Ljava/lang/String;IIIIZI)V",NULL},{"HIDDeviceDisconnected","(I)V",NULL},{"HIDDeviceInputReport","(I[B)V",NULL},{"HIDDeviceOpenPending","(I)V",NULL},{"HIDDeviceOpenResult","(IZ)V",NULL},{"HIDDeviceReportResponse","(I[B)V",NULL}};
methods[0].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceRegisterCallback");if(!methods[0].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[1].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceReleaseCallback");if(!methods[1].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[2].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceConnected");if(!methods[2].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[3].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceDisconnected");if(!methods[3].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[4].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceInputReport");if(!methods[4].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[5].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceOpenPending");if(!methods[5].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[6].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceOpenResult");if(!methods[6].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[7].fnPtr=dlsym(lib,"Java_org_libsdl_app_HIDDeviceManager_HIDDeviceReportResponse");if(!methods[7].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
if((*env)->RegisterNatives(env,c,methods,sizeof(methods)/sizeof(methods[0]))!=JNI_OK){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}(*env)->DeleteLocalRef(env,c);}
{ jclass c=(*env)->FindClass(env,"org/vtsdlx/app/SDLActivity");if(!c)return JNI_FALSE;
JNINativeMethod methods[]={{"nativeAddTouch","(ILjava/lang/String;)V",NULL},{"nativeAllowRecreateActivity","()Z",NULL},{"nativeCheckSDLThreadCounter","()I",NULL},{"nativeCleanupMainThread","()V",NULL},{"nativeFocusChanged","(Z)V",NULL},{"nativeGetHint","(Ljava/lang/String;)Ljava/lang/String;",NULL},{"nativeGetHintBoolean","(Ljava/lang/String;Z)Z",NULL},{"nativeGetVersion","()Ljava/lang/String;",NULL},{"nativeInitMainThread","()V",NULL},{"nativeLowMemory","()V",NULL},{"nativePause","()V",NULL},{"nativePermissionResult","(IZ)V",NULL},{"nativeQuit","()V",NULL},{"nativeResume","()V",NULL},{"nativeRunMain","(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)I",NULL},{"nativeSendQuit","()V",NULL},{"nativeSetNaturalOrientation","(I)V",NULL},{"nativeSetScreenResolution","(IIIIFF)V",NULL},{"nativeSetenv","(Ljava/lang/String;Ljava/lang/String;)V",NULL},{"nativeSetupJNI","()V",NULL},{"onNativeAccel","(FFF)V",NULL},{"onNativeClipboardChanged","()V",NULL},{"onNativeDarkModeChanged","(Z)V",NULL},{"onNativeDropFile","(Ljava/lang/String;)V",NULL},{"onNativeFileDialog","(I[Ljava/lang/String;I)V",NULL},{"onNativeInsetsChanged","(IIII)V",NULL},{"onNativeKeyDown","(I)V",NULL},{"onNativeKeyUp","(I)V",NULL},{"onNativeKeyboardFocusLost","()V",NULL},{"onNativeLocaleChanged","()V",NULL},{"onNativeMouse","(IIFFZ)V",NULL},{"onNativePen","(IIIIFFF)V",NULL},{"onNativePinchEnd","()V",NULL},{"onNativePinchStart","()V",NULL},{"onNativePinchUpdate","(F)V",NULL},{"onNativeResize","()V",NULL},{"onNativeRotationChanged","(I)V",NULL},{"onNativeScreenKeyboardHidden","()V",NULL},{"onNativeScreenKeyboardShown","()V",NULL},{"onNativeSoftReturnKey","()Z",NULL},{"onNativeSurfaceChanged","()V",NULL},{"onNativeSurfaceCreated","()V",NULL},{"onNativeSurfaceDestroyed","()V",NULL},{"onNativeTouch","(IIIFFF)V",NULL}};
methods[0].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeAddTouch");if(!methods[0].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[1].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeAllowRecreateActivity");if(!methods[1].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[2].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeCheckSDLThreadCounter");if(!methods[2].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[3].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeCleanupMainThread");if(!methods[3].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[4].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeFocusChanged");if(!methods[4].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[5].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeGetHint");if(!methods[5].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[6].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeGetHintBoolean");if(!methods[6].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[7].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeGetVersion");if(!methods[7].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[8].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeInitMainThread");if(!methods[8].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[9].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeLowMemory");if(!methods[9].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[10].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativePause");if(!methods[10].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[11].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativePermissionResult");if(!methods[11].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[12].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeQuit");if(!methods[12].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[13].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeResume");if(!methods[13].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[14].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeRunMain");if(!methods[14].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[15].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeSendQuit");if(!methods[15].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[16].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeSetNaturalOrientation");if(!methods[16].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[17].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeSetScreenResolution");if(!methods[17].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[18].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeSetenv");if(!methods[18].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[19].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_nativeSetupJNI");if(!methods[19].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[20].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeAccel");if(!methods[20].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[21].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeClipboardChanged");if(!methods[21].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[22].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeDarkModeChanged");if(!methods[22].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[23].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeDropFile");if(!methods[23].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[24].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeFileDialog");if(!methods[24].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[25].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeInsetsChanged");if(!methods[25].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[26].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeKeyDown");if(!methods[26].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[27].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeKeyUp");if(!methods[27].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[28].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeKeyboardFocusLost");if(!methods[28].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[29].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeLocaleChanged");if(!methods[29].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[30].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeMouse");if(!methods[30].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[31].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativePen");if(!methods[31].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[32].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativePinchEnd");if(!methods[32].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[33].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativePinchStart");if(!methods[33].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[34].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativePinchUpdate");if(!methods[34].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[35].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeResize");if(!methods[35].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[36].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeRotationChanged");if(!methods[36].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[37].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeScreenKeyboardHidden");if(!methods[37].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[38].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeScreenKeyboardShown");if(!methods[38].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[39].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeSoftReturnKey");if(!methods[39].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[40].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeSurfaceChanged");if(!methods[40].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[41].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeSurfaceCreated");if(!methods[41].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[42].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeSurfaceDestroyed");if(!methods[42].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[43].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLActivity_onNativeTouch");if(!methods[43].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
if((*env)->RegisterNatives(env,c,methods,sizeof(methods)/sizeof(methods[0]))!=JNI_OK){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}(*env)->DeleteLocalRef(env,c);}
{ jclass c=(*env)->FindClass(env,"org/vtsdlx/app/SDLAudioManager");if(!c)return JNI_FALSE;
JNINativeMethod methods[]={{"nativeAddAudioDevice","(ZLjava/lang/String;I)V",NULL},{"nativeRemoveAudioDevice","(ZI)V",NULL},{"nativeSetupJNI","()V",NULL}};
methods[0].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLAudioManager_nativeAddAudioDevice");if(!methods[0].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[1].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLAudioManager_nativeRemoveAudioDevice");if(!methods[1].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[2].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLAudioManager_nativeSetupJNI");if(!methods[2].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
if((*env)->RegisterNatives(env,c,methods,sizeof(methods)/sizeof(methods[0]))!=JNI_OK){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}(*env)->DeleteLocalRef(env,c);}
{ jclass c=(*env)->FindClass(env,"org/vtsdlx/app/SDLControllerManager");if(!c)return JNI_FALSE;
JNINativeMethod methods[]={{"nativeAddHaptic","(ILjava/lang/String;)V",NULL},{"nativeAddJoystick","(ILjava/lang/String;Ljava/lang/String;IIIIIIZZZZ)V",NULL},{"nativeRemoveHaptic","(I)V",NULL},{"nativeRemoveJoystick","(I)V",NULL},{"nativeSetupJNI","()V",NULL},{"onNativeHat","(IIII)V",NULL},{"onNativeJoy","(IIF)V",NULL},{"onNativeJoySensor","(IIJFFF)V",NULL},{"onNativePadDown","(III)Z",NULL},{"onNativePadUp","(III)Z",NULL}};
methods[0].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_nativeAddHaptic");if(!methods[0].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[1].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_nativeAddJoystick");if(!methods[1].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[2].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_nativeRemoveHaptic");if(!methods[2].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[3].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_nativeRemoveJoystick");if(!methods[3].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[4].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_nativeSetupJNI");if(!methods[4].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[5].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_onNativeHat");if(!methods[5].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[6].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_onNativeJoy");if(!methods[6].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[7].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_onNativeJoySensor");if(!methods[7].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[8].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_onNativePadDown");if(!methods[8].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[9].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLControllerManager_onNativePadUp");if(!methods[9].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
if((*env)->RegisterNatives(env,c,methods,sizeof(methods)/sizeof(methods[0]))!=JNI_OK){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}(*env)->DeleteLocalRef(env,c);}
{ jclass c=(*env)->FindClass(env,"org/vtsdlx/app/SDLInputConnection");if(!c)return JNI_FALSE;
JNINativeMethod methods[]={{"nativeCommitText","(Ljava/lang/String;I)V",NULL},{"nativeGenerateScancodeForUnichar","(C)V",NULL}};
methods[0].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLInputConnection_nativeCommitText");if(!methods[0].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
methods[1].fnPtr=dlsym(lib,"Java_org_libsdl_app_SDLInputConnection_nativeGenerateScancodeForUnichar");if(!methods[1].fnPtr){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}
if((*env)->RegisterNatives(env,c,methods,sizeof(methods)/sizeof(methods[0]))!=JNI_OK){(*env)->DeleteLocalRef(env,c);return JNI_FALSE;}(*env)->DeleteLocalRef(env,c);}
ready=1;__android_log_print(4,"TurboVita","Relocated SDL native methods registered");return JNI_TRUE;}