from pathlib import Path
import json,hashlib,shutil
W=Path(r'E:\ESTUDO APK\work\station-theme-collections-r39-20261006')
c=json.loads((W/'data/metadata-coverage.json').read_text('utf8'))
platforms=c['platforms'];totals={k:sum(x[k] for x in platforms.values()) for k in ('games','complete','missingRatings','missingPlayers')}
lines=['# Metadados de jogos — R39 — 06/10/2026','','Fonte pública: https://gamesdb.launchbox-app.com/Metadata.zip. Snapshot e SHA da fonte em `evidence`/backup de metadados. Estes XMLs contêm fatos (nome, plataforma, máximo de jogadores, avaliação e votos), não ROMs, links de download nem autorização para publicar jogos.','','O catálogo de download continua vindo do servidor Station autenticado. Estes arquivos não criam plataformas nem jogos no catálogo. O índice nativo gerado procura plataforma + título/alias exato, com normalização conservadora. IDs atuais têm prioridade. Casos ambíguos não são adivinhados.','','## Cobertura verificável','',f"Catálogo atual: {c['catalogItems']} itens; 2.211 com jogadores, 2.211 com nota. As duas lacunas são títulos diferentes: jogadores de Super Mario World (hack Mega Drive Chuanpu/Jazz) e nota de Dragon’s Heaven (development board, Neo Geo). Consulte `current-metadata-pending.json`.",'','2.096 correspondências públicas únicas. Notas públicas exigem votos > 0 e são convertidas de 0–5 para 0–1 no XML/0–1000 no índice. Outros valores existentes do XML são preservados com procedência própria; não representam necessariamente uma média pública. Traduções BR herdam a avaliação da edição-base quando documentado no audit.','','Preparação futura: '+str(len(platforms))+' plataformas, '+str(totals['games'])+' registros de metadados, '+str(totals['complete'])+' com ambos os campos. '+str(totals['missingRatings'])+' sem avaliação e '+str(totals['missingPlayers'])+' sem jogadores na fonte (grupos podem se sobrepor). Ausência permanece explícita; nunca preencher com zero/cinco estrelas ou número inventado.','','Inclui plataformas clássicas até Xbox 360 e mantém em grupo separado os sistemas mais recentes já presentes no aplicativo (3DS, Wii U, Vita e Switch). Não representa uma lista completa de todos os jogos já lançados.','','Para acrescentar/corrigir: consultar fonte verificável, registrar alias exato por plataforma se necessário, executar pipeline e testes, conferir diferenças do índice e recompilar. Não usar `DatabaseID` como URL de página: o site e o dump podem ter identificadores diferentes.','','| Plataforma | Jogos | Com ambos | Sem nota | Sem jogadores |','|---|---:|---:|---:|---:|']
for k,v in sorted(platforms.items()):lines.append(f"| {k} | {v['games']} | {v['complete']} | {v['missingRatings']} | {v['missingPlayers']} |")
(W/'metadata-xml/README.md').write_text('\n'.join(lines)+'\n','utf8')
d=Path(r'E:\ESTUDO APK\work\turbostations-reconstruction-20261002\decompiled')
e={'scope':'Static evidence + host execution of shared production helpers; Android reproduction pending','decompilationImageBase':'0x100000','nativeFunctions':{'closeSearch':'0x219570','setSearchQuery':'0x21c414','rebuildVisible':'0x21b134','input':'0x2354d4','touch':'0x234878'},'observations':['Direct query-string clears on 4 transitions left native search tokens unchanged. Replaced by native closeSearch(clear=true) before changing facade/scope.','Native input routes Android AC_BACK past closeSearch with non-pad keyboard. Shared Back now explicitly closes search; subsequent Back clears query.','Original rebuild treats empty visible list as invalid every frame. Reuse only a completed empty search with unchanged owner/catalog/storage/revision/query/platform/installed flag. Navigation invalidates explicitly.','Original full-text branch bypasses platform and installed conditions. Postfilter now enforces both, then existing folder filter.','No-result view offers Clear/Edit; IME view offers Clear/Show results using existing native routes. Touch uses native types 0=down/1=move/2=up. No simulated coordinate navigation.'],'sourceFiles':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [d/'00319570_GuiStore__closeSearch.c',d/'0031c414_GuiStore__setSearchQuery.c',d/'0031b134_GuiStore__rebuildVisible.c',d/'003354d4_GuiStore__input.c',d/'00334878_GuiStore__touch.c']}}
(W/'evidence/search-diagnosis.json').write_text(json.dumps(e,indent=2),'utf8')
print(json.dumps(totals))
