from pathlib import Path
W=Path(r'E:\ESTUDO APK\work\station-theme-collections-r39-20261006');N=W/'native'
p=N/'station_theme_palette.h';s=p.read_text('utf8');a=s.index('static StationThemeRect stationThemeChoice');b=s.index('static bool stationThemeContains',a);s=s[:a]+s[b:];a=s.index('// Cancelled drags');s=s[:a];p.write_text(s,'utf8')
p=N/'native_settings.h';s=p.read_text('utf8').replace('static StationThemeGesture settingsThemeGesture;','').replace('settingsThemeGesture={};','').replace('if(touchThemeSwitch(p,event,true)){settingsRefreshThemeLabels();return true;}','if(touchThemeSwitch(p,event,true)){settingsRefreshThemeLabels(stationThemeSaveFailed);return true;}');p.write_text(s,'utf8')
p=N/'native_theme_switch.h';s=p.read_text('utf8').replace('static StationThemeTransition stationThemeTransition;','static bool stationThemeSaveFailed;\nstatic StationThemeTransition stationThemeTransition;').replace('bool saved=stationThemeChoose(1-stationThemeId);log','bool saved=stationThemeChoose(1-stationThemeId);stationThemeSaveFailed=!saved;log');p.write_text(s,'utf8')
# Missing community score is an explicit label, not a fabricated zero-star rating.
p=N/'native_info.h';s=p.read_text('utf8').replace('static unsigned infoStarsStarted;','static unsigned infoStarsStarted;\nstatic void*infoRatingUnknown;');s=s.replace('infoPlayersText=createInfoText(p,0xD1DED5ff);oldIndex=-2;','infoPlayersText=createInfoText(p,0xD1DED5ff);infoRatingUnknown=createInfoText(p,0xD1DED5ff);setLongText(infoRatingUnknown,"SEM NOTA");oldIndex=-2;');s=s.replace('return t==infoTitle||','return t==infoRatingUnknown||t==infoTitle||');s=s.replace('auto row=infoPlayStars;float size=row.h,step=size*1.15f;','auto row=infoPlayStars;float size=row.h,step=size*1.15f;\n if(!infoDetails||infoDetails->ratingThousandths<0){static float x=-1,y=-1,width=-1,height=-1;if(row.x!=x||row.y!=y||row.w!=width||row.h!=height){x=row.x;y=row.y;width=row.w;height=row.h;fitInfoText(infoRatingUnknown,row,.38f,0);}fn<void(*)(void*,void*)>(0x2d2dc4)(infoRatingUnknown,&formationMatrix);return;}');p.write_text(s,'utf8')
# Replace obsolete two-button gesture tests with the actual shared Lottie toggle.
p=Path('r39_tests.cpp');s=p.read_text('utf8').replace('#include "station_lottie_once.h"','#include "station_lottie_once.h"\n#include "station_theme_switch_state.h"');s=s.replace('auto a=stationThemeChoice(w,h,0),b=stationThemeChoice(w,h,1);','auto a=stationThemeToggleRect(w,h,true),b=stationThemeToggleRect(w,h,false);').replace('a.x+a.w<b.x&&b.x+b.w<w*.965f&&a.y+a.h<h*.235f&&a.y>h*.139f','b.x+b.w<w*.965f&&b.y>h*.945f&&b.y+b.h<h&&a.y+a.h<h*.235f&&a.y>h*.139f');s=s.replace('stationThemeChoice(w,h,i)','stationThemeToggleRect(w,h,i==1)').replace('StationThemeGesture g','StationThemeToggleGesture g');s=s.replace('x,y,w,h','x,y,r').replace('0,0,w,h','0,0,r');s=s.replace('==-2','==0').replace('==i);assert(g.touch','==1);assert(g.touch').replace('==i);checks','==1);checks').replace('!g.active','!g.pressed');p.write_text(s,'utf8')
print('Removed obsolete theme controls; added honest missing-rating label and current gesture tests.')
