"""Read-only structural check of R78 synopsis identity, provenance and generated bytes.

Reads metadata XML only, never ROMs. This does not fact-check every sentence,
compile an APK, exercise Android, or call a server. Its output goes to E:.
"""
from pathlib import Path
from collections import Counter
from datetime import datetime, timezone
import argparse
import hashlib
import json
import re
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
XML_ROOT = Path(r'G:\TURBORAMA\RetroBat\roms')
DEFAULT_OUTPUT = Path(r'E:\ESTUDO APK\work\station-synopses-r78-20261008\structural-check')
LABELS = {'snes': 'Super Nintendo', 'snesbr': 'Super Nintendo - BR', 'megadrive': 'MegaDrive',
          'megadrivebr': 'MegaDrive - BR', 'n64': 'Nintendo 64', 'neogeo': 'Neo Geo', 'neogeocd': 'Neo Geo CD'}
PLACEHOLDERS = {'sem sinopse', 'sem descrição', 'sinopse indisponível', 'descrição indisponível',
                'sinopse em preparação', 'sinopse em preparação para este jogo',
                'sinopse não disponível', 'descrição não disponível', 'no description',
                'no description available', 'no synopsis', 'n/a', 'unknown'}
COUNTS = Counter()


def check(condition, group, context=''):
    if not condition:
        raise AssertionError(group + ': ' + context)
    COUNTS[group] += 1


def digest(raw):
    return hashlib.sha256(raw).hexdigest()


def read(relative):
    return json.loads((ROOT / relative).read_text('utf8'))


def identity_map(rows, group):
    result = {row['itemId']: row for row in rows}
    check(len(result) == len(rows), group, 'duplicate item ID')
    return result


def paged_reference(text):
    # Independent straightforward byte walk following the retained 800/1200
    # policy. The separate native suite compares the actual C++ implementation.
    data = text.encode('utf8')
    segments = []
    pos = 0
    while pos < len(data):
        stop = min(len(data), pos + 800)
        if stop < len(data):
            while stop > pos and (data[stop] & 192) == 128:
                stop -= 1
            boundary = stop
            while boundary >= 0 and data[boundary] not in b' \n\t':
                boundary -= 1
            if boundary > pos + 400:
                stop = boundary
            else:
                boundary = stop
                while boundary < len(data) and data[boundary] not in b' \n\t':
                    boundary += 1
                stop = min(boundary, pos + 1200, len(data))
                while stop < len(data) and stop > pos and (data[stop] & 192) == 128:
                    stop -= 1
        segments.append(data[pos:stop])
        pos = stop
        while pos < len(data) and data[pos] in b' \n\t':
            pos += 1
    return b'\f'.join(segments).decode('utf8')


def header_fields(section, final_count):
    strings = r'"(?:\\.|[^"\\])*"'
    pattern = re.compile(r'^\{(' + strings + r'(?:,' + strings + r')*)' + final_count + r'\},$', re.M)
    return [json.loads('[' + found.replace(r'\?', '?') + ']') for found in pattern.findall(section)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    audit = identity_map(read('catalog/existing-synopses-audit.json')['records'], 'audit-unique')
    inventory = identity_map(json.loads((ROOT.parent / 'station-multiplayer-r77-20261008/catalog/catalog-inventory.json').read_text('utf8'))['records'], 'inventory-unique')
    completed_rows = read('data/synopses-complete.json')
    completed = identity_map(completed_rows, 'completed-unique')
    aliases = read('data/exact-alias-bindings.json')
    restorations = read('data/exact-prefix-restorations.json')
    editorial = read('data/editorial-synopses.json')
    overrides = read('data/exact-server-overrides.json')
    proposals = read('data/server-synopsis-candidates.json')
    native_only = read('data/native-only-descriptions.json')
    check(set(completed) == set(audit) == set(inventory) and len(completed) == 2467, 'catalog-coverage')
    check(sum(row['catalogVisible'] for row in completed_rows) == 2212, 'catalog-coverage')
    check(list(completed) == sorted(completed), 'catalog-order')
    check(set(row['platform'] for row in completed_rows) == set(LABELS), 'platform-coverage')
    changed = set()
    for item_id, row in completed.items():
        old = audit[item_id]
        inv = inventory[item_id]
        for key in ('platform', 'name', 'catalogVisible', 'artifactSha256', 'artifactFileName', 'artifactLaunchPath', 'contentSha256'):
            check(row[key] == old[key] == inv[key], 'identity-unchanged', item_id + '/' + key)
        check(row['catalogItemRevision'] == old['itemRevision'] == inv['itemRevision'], 'identity-unchanged', item_id)
        check(row['catalogRevision'] == inv['catalogRevision'] == 14, 'identity-unchanged', item_id)
        check(row['label'] == LABELS[row['platform']], 'platform-label', item_id)
        text = row['description']
        check(bool(text.strip()) and text.strip().casefold().rstrip('.') not in PLACEHOLDERS, 'prose-present', item_id)
        check(text.strip().casefold() != row['name'].strip().casefold(), 'not-title-only', item_id)
        check('\ufffd' not in text and '\x00' not in text and not any(0xd800 <= ord(c) <= 0xdfff for c in text), 'text-encoding', item_id)
        check(digest(text.encode('utf8')) == row['descriptionSha256'], 'description-digest', item_id)
        check(row['onlineAuthorizationChanged'] is False and row['variantSpecificBehaviorInvented'] is False, 'scope-preserved', item_id)
        if text != old['selectedDescription']:
            changed.add(item_id)

    native_header = (ROOT / 'native/station_game_infos.h').read_text('utf8')
    game_part, override_part = native_header.split('static const StationSynopsisReviewedOverride stationSynopsisReviewedOverrides[]={', 1)
    header_rows = header_fields(game_part, ',1')
    check(len(header_rows) == 2467, 'header-coverage')
    for fields, row in zip(header_rows, completed_rows):
        expected = [row['label'], row['itemId'], row['name'], row['description'], 'station-synopsis:r78:' + row['sourceKind'] + ':' + row['descriptionSha256']]
        check(fields == expected, 'header-exact-json', row['itemId'])
    override_header = header_fields(override_part, '')
    check(override_header == [[row[key] for key in ('itemId', 'previousRaw', 'previousPaged')] for row in overrides], 'override-header-exact-json')

    check(len(aliases) == 6, 'alias-count')
    for row in aliases:
        target, source = inventory[row['targetItemId']], inventory[row['sourceItemId']]
        for key, value in row['descriptor'].items():
            check(target[key] == source[key] == value, 'alias-exact-descriptor', key)
        check(audit[row['targetItemId']]['selectedDescription'] == '', 'alias-original-empty')
        check(completed[row['targetItemId']]['description'] == completed[row['sourceItemId']]['description'], 'alias-exact-description')
        check(row['promotedForDescriptionOnly'] is True and row['onlineAuthorizationChanged'] is False, 'alias-scope')

    check(len(restorations) == 17, 'restoration-count')
    source_index = {row['sourceId']: row for row in read('catalog/coverage.json')['sources']}
    xml_cache = {}
    for row in restorations:
        old = audit[row['itemId']]
        text = row['description']
        check(len(old['selectedDescription']) == 2000 and text.startswith(old['selectedDescription']) and len(text) > 2000, 'restoration-integral-prefix', row['itemId'])
        check(completed[row['itemId']]['description'] == text and digest(text.encode('utf8')) == row['descriptionSha256'], 'restoration-exact-output', row['itemId'])
        check(digest(old['selectedDescription'].encode('utf8')) == row['replacesDescriptionSha256'], 'restoration-original-digest', row['itemId'])
        for proof in row['sources']:
            sid = proof['sourceId']
            if sid not in xml_cache:
                path = (XML_ROOT / sid.removeprefix('retrobat/')).resolve()
                check(path.is_relative_to(XML_ROOT.resolve()) and path.name == 'gamelist.xml', 'xml-metadata-path')
                raw = path.read_bytes()
                check(digest(raw) == source_index[sid]['sha256'] == proof['sourceFileSHA256'], 'xml-source-digest', sid)
                check(b'<!DOCTYPE' not in raw.upper() and b'<!ENTITY' not in raw.upper(), 'xml-no-external-entities', sid)
                xml_cache[sid] = ET.fromstring(raw).findall('game')
            game = xml_cache[sid][proof['ordinal'] - 1]
            check(game.findtext('desc', '') == text, 'xml-exact-prose', row['itemId'])
            check(game.findtext('path', '').replace('\\', '/').removeprefix('./') == proof['path'], 'xml-exact-file', row['itemId'])
            check(proof['descriptionSha256'] == row['descriptionSha256'], 'xml-exact-prose-digest', row['itemId'])

    check(len(editorial) == 19 and sum(row['apply'] is True for row in editorial) == 14, 'editorial-count')
    for row in editorial:
        old = audit[row['itemId']]
        check(old['platform'] == row['platform'] and old['name'] == row['name'], 'editorial-exact-identity')
        check(old['selectedDescription'] == row['replaceDescriptionExact'] and old['selectedDescriptionSha256'] == row['replacesDescriptionSha256'], 'editorial-exact-previous-text')
        check(row['description'] == completed[row['itemId']]['description'], 'editorial-exact-output')
        if not row['apply']:
            check(completed[row['itemId']]['description'] == old['selectedDescription'], 'editorial-pending-preserved')
    expected_changed = {row['targetItemId'] for row in aliases} | {row['itemId'] for row in restorations} | {row['itemId'] for row in editorial if row['apply']}
    check(changed == expected_changed and len(changed) == 37, 'only-reviewed-changes')
    expected_overrides = {row['itemId'] for row in restorations} | {row['itemId'] for row in editorial if row['apply']} | {'ab9773189dbfc1571ca0d56adb13ff32'}
    check({row['itemId'] for row in overrides} == expected_overrides and len(overrides) == 32, 'override-coverage')
    for row in overrides:
        check(row['previousRaw'] == audit[row['itemId']]['publishedServerDescription'], 'override-published-raw', row['itemId'])
        check(row['previousPaged'] == paged_reference(row['previousRaw']), 'override-byte-pages', row['itemId'])

    check(proposals['applied'] is False and proposals['changesJavaContract'] is False, 'server-not-applied')
    check(len(proposals['proposals']) == 64 and len(native_only) == 17, 'server-proposal-count')
    for proposal in proposals['proposals']:
        before = proposal['precondition']
        old = audit[before['itemId']]
        row = completed[before['itemId']]
        for key in ('platform', 'itemRevision', 'artifactSha256'):
            check(before[key] == old[key], 'cas-exact-identity', key)
        check(before['previousDescription'] == old['publishedServerDescription'] and before['previousDescriptionSha256'] == old['publishedServerDescriptionSha256'], 'cas-exact-old-text')
        check(proposal['proposedDescription'] == row['description'] and proposal['proposedDescriptionSha256'] == row['descriptionSha256'], 'cas-exact-new-text')
        check(len(row['description'].encode('utf-16-le')) // 2 == proposal['utf16CodeUnits'] <= 2000, 'cas-utf16-limit')
        check(proposal['applied'] is False and proposal['changesOnlineAuthorization'] is False, 'cas-review-only')
    check({row['itemId'] for row in native_only} == {row['itemId'] for row in restorations}, 'native-only-exact-restorations')
    for row in native_only:
        text = completed[row['itemId']]['description']
        check(len(text.encode('utf-16-le')) // 2 == row['utf16CodeUnits'] > 2000 and row['serverUpdateProposed'] is False, 'native-only-contract-limit')

    checked_files = ['data/synopses-complete.json', 'data/exact-alias-bindings.json', 'data/exact-prefix-restorations.json',
                     'data/editorial-synopses.json', 'data/exact-server-overrides.json', 'data/server-synopsis-candidates.json',
                     'data/native-only-descriptions.json', 'native/station_game_infos.h', 'catalog/existing-synopses-audit.json']
    result = {'utc': datetime.now(timezone.utc).isoformat(), 'result': 'passed', 'checks': sum(COUNTS.values()),
              'checksByGroup': dict(COUNTS), 'catalogIds': 2467, 'visibleIds': 2212, 'compatibilityIds': 255,
              'emptyDescriptions': 0, 'exactAliasBindings': 6, 'xmlPrefixRestorations': 17, 'editorialUpdates': 14,
              'editorialPendingPreserved': 5, 'exactOverrides': 32, 'serverReviewProposals': 64, 'nativeOnlyLongTexts': 17,
              'fileSHA256': {path: digest((ROOT / path).read_bytes()) for path in checked_files},
              'recipeSHA256': digest(Path(__file__).read_bytes()), 'romRead': False, 'serverChanged': False,
              'apkCompiled': False, 'androidTested': False, 'allHistoricalFactsVerified': False,
              'limits': ['Structural identity/provenance/encoding checks do not verify every historical fact.',
                         'Paging consistency here is Python-only; the native suite separately executes retained C++.',
                         'No runtime, player capacity, profile or online permission is changed.']}
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / 'synopses-structure.json').write_text(json.dumps(result, ensure_ascii=False, indent=2) + '\n', encoding='utf8')
    print(json.dumps(result, ensure_ascii=False))


if __name__ == '__main__':
    main()
