package org.emulationstation.frontend.netplay;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;import java.lang.reflect.*;import java.util.*;import java.util.concurrent.*;
public final class StationSessionLifecycleTest {
 static int checks;static final String ROOM="0123456789abcdef0123456789abcdef";
 static void yes(boolean v){checks++;if(!v)throw new AssertionError("lifecycle check "+checks);}
 static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 static JSONObject room(){return new JSONObject().put("roomId",ROOM).put("generation",3).put("recoveryProtocol","station-stream.v2").put("engineId","fixture").put("coreSha256","fixture").put("runtimeSha256","fixture").put("contentSha256","fixture").put("optionsSha256","fixture");}
 static void await(String command,long count)throws Exception{long deadline=System.nanoTime()+TimeUnit.SECONDS.toNanos(3);while(StationOnlineClient.count(command)<count&&System.nanoTime()<deadline)Thread.sleep(2);yes(StationOnlineClient.count(command)==count);}
 static final class F {
  Activity a=new Activity();StationSessionService service=new StationSessionService();Intent intent=StationGameSession.attach(a,room(),new Intent());String key=intent.getStringExtra(StationGameSession.ANCHOR_EXTRA);StationGameSession owner=StationGameSession.anchorOwner(key,ROOM,3);ResultReceiver events=StationSessionChannel.read(intent.getExtras(),StationGameSession.EXTRA);int ready,errors;String error;
  StationSessionLink link=new StationSessionLink(a,key,ROOM,3,new StationSessionLink.Listener(){public void ready(){ready++;}public void unavailable(String category){errors++;error=category;}});
  void open(){link.bind();a.connect(service);Handler.drain();}
  void stop(){link.close();Handler.drain();service.onUnbind(new Intent());owner.anchorEnded();service.onDestroy();Handler.drain();}
 }
 static Bundle identity(F f){Bundle b=new Bundle();b.putString("session",f.key);b.putString("room",ROOM);b.putLong("generation",3);b.putInt("attempt",1);return b;}
 static class Reply {int attached,rejected;Messenger endpoint=new Messenger(new Handler(Looper.getMainLooper(),m->{if(m.what==3)attached++;if(m.what==4)rejected++;return true;}));}
 static void attach(F f,Reply p,Bundle data,int uid)throws Exception{Message m=Message.obtain(null,1);m.replyTo=p.endpoint;m.setData(data);android.os.Process.uid=uid;try{new Messenger(f.service.onBind(new Intent())).send(m);}finally{android.os.Process.uid=1001;}Handler.drain();}
 public static void main(String[] args)throws Exception{
  F f=new F();boolean duplicate=false;try{StationGameSession.attach(new Activity(),room(),new Intent());}catch(IllegalArgumentException expected){duplicate=true;}yes(duplicate);yes(StationGameSession.anchorOwner(f.key,ROOM,3)==f.owner);f.link.bind();yes(f.a.binds==1&&f.ready==0);f.link.bind();yes(f.a.binds==1);yes(f.a.flags==(Context.BIND_AUTO_CREATE|Context.BIND_IMPORTANT));yes(f.a.intent.target==StationSessionService.class);f.a.connect(f.service);Handler.drain();yes(f.ready==1);f.a.connect(f.service);Handler.drain();yes(f.ready==1);f.link.close();Handler.drain();yes(f.a.unbinds==1);f.link.close();yes(f.a.unbinds==1);yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);f.stop();
  f=new F();f.link.bind();ServiceConnection old=f.a.connection;f.link.close();old.onServiceConnected(new ComponentName(),f.service.onBind(new Intent()));Handler.drain();yes(f.ready==0&&f.a.unbinds==1);f.stop();
  f=new F();f.link.bind();f.a.connect(f.service);f.link.close();Handler.drain();yes(f.ready==0);yes(f.a.unbinds==1);yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);f.stop();
  f=new F();f.a.accept=false;f.link.bind();yes(f.a.unbinds==1&&f.ready==0&&"BIND_UNAVAILABLE".equals(f.error));f.stop();
  f=new F();f.a.throwsBind=true;f.link.bind();yes(f.a.unbinds==1&&f.ready==0&&"BIND_FAILED".equals(f.error));f.stop();
  f=new F();f.open();old=f.a.connection;old.onServiceDisconnected(new ComponentName());yes(f.a.unbinds==0&&"BINDER_DISCONNECTED".equals(f.error));old.onServiceConnected(new ComponentName(),f.service.onBind(new Intent()));Handler.drain();yes(f.ready==2&&f.a.binds==1);f.stop();
  f=new F();f.open();old=f.a.connection;old.onBindingDied(new ComponentName());yes(f.a.unbinds==1&&f.a.binds==2&&"BINDING_DIED".equals(f.error));old.onServiceConnected(new ComponentName(),f.service.onBind(new Intent()));Handler.drain();yes(f.ready==1);f.a.connect(f.service);Handler.drain();yes(f.ready==2);f.stop();
  f=new F();f.link.bind();f.a.connection.onNullBinding(new ComponentName());yes(f.a.unbinds==1&&f.a.binds==1&&"NULL_BINDING".equals(f.error));f.stop();
  f=new F();Reply p=new Reply();Bundle wrong=identity(f);wrong.putString("session","87654321-1234-1234-1234-123456789abc");attach(f,p,wrong,1001);yes(p.rejected==1&&p.attached==0);wrong=identity(f);wrong.putString("room","1123456789abcdef0123456789abcdef");attach(f,p,wrong,1001);yes(p.rejected==2);wrong=identity(f);wrong.putLong("generation",4);attach(f,p,wrong,1001);yes(p.rejected==3);attach(f,p,identity(f),2002);yes(p.rejected==3&&p.attached==0);attach(f,p,identity(f),1001);yes(p.attached==1);Reply q=new Reply();attach(f,q,identity(f),1001);yes(q.rejected==1&&q.attached==0);((Messenger.Endpoint)p.endpoint.getBinder()).die();Handler.drain();yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);yes(StationOnlineClient.count("leave")==0&&StationOnlineClient.count("recovery-failed")==0);f.stop();
  f=new F();p=new Reply();((Messenger.Endpoint)p.endpoint.getBinder()).die();attach(f,p,identity(f),1001);yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);yes(p.attached==0);f.stop();
  f=new F();f.link.bind();f.a.connect(f.service);Messenger replies=(Messenger)field(f.link,"replies");Message forged=Message.obtain(null,3);Bundle bad=identity(f);bad.putInt("attempt",2);forged.setData(bad);replies.send(forged);Handler.drain();yes(f.ready==1);f.stop();
  // Cross-endpoint order reversed: local detach first must not invent recovery-failed or suppress a human exit.
  f=new F();f.open();f.link.close();Handler.drain();yes(StationOnlineClient.count("leave")==0&&StationOnlineClient.count("recovery-failed")==0);f.events.send(4,null);f.events.send(4,null);Handler.drain();await("leave",1);yes(StationOnlineClient.count("recovery-failed")==0);f.events.send(6,null);Handler.drain();yes(StationOnlineClient.count("recovery-failed")==0);f.stop();
  f=new F();f.open();f.events.send(4,null);Handler.drain();f.link.close();Handler.drain();await("leave",2);yes(StationOnlineClient.count("recovery-failed")==0);f.stop();
  // An actual terminal event sent by the Activity is still honoured if local DETACH is delivered first.
  f=new F();f.open();f.link.close();Handler.drain();f.events.send(6,null);f.events.send(6,null);Handler.drain();await("recovery-failed",1);yes(StationOnlineClient.count("leave")==2);f.events.send(4,null);Handler.drain();await("leave",3);f.stop();
  // Two timeout/retry callbacks while one HTTP grant request is pending cannot mint parallel grants.
  f=new F();f.open();StationOnlineClient.ticketEntered=new CountDownLatch(1);StationOnlineClient.ticketRelease=new CountDownLatch(1);f.events.send(1,null);f.events.send(5,null);Handler.drain();yes(StationOnlineClient.ticketEntered.await(2,TimeUnit.SECONDS));for(int i=0;i<20;i++)f.events.send(5,null);Handler.drain();yes(StationOnlineClient.count("resume-relay")==1);StationOnlineClient.ticketRelease.countDown();f.events.send(4,null);Handler.drain();await("leave",4);f.stop();StationOnlineClient.ticketEntered=null;StationOnlineClient.ticketRelease=null;
  // Actual LaunchReturn methods used by Rooms.onActivityResult; no Binder can clean a pre-ATTACH crash.
  StationGameSession.LaunchReturn result=new StationGameSession.LaunchReturn();f=new F();int code=result.prepare(f.intent,ROOM,3);yes(result.pending());yes(!result.completed(code+1));yes(StationGameSession.anchorOwner(f.key,ROOM,3)==f.owner);
  boolean pendingRejected=false;try{result.prepare(f.intent,ROOM,3);}catch(IllegalStateException expected){pendingRejected=true;}yes(pendingRejected);
  // Android RESULT_CANCELED/normal return both complete the request; never infer human intent.
  yes(result.completed(code));yes(!result.pending());yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);yes(StationOnlineClient.count("leave")==4&&StationOnlineClient.count("recovery-failed")==1);f.stop();
  f=new F();int second=result.prepare(f.intent,ROOM,3);yes(second>code);yes(!result.completed(code));yes(StationGameSession.anchorOwner(f.key,ROOM,3)==f.owner);
  Bundle configuration=result.save();StationGameSession.LaunchReturn recreated=new StationGameSession.LaunchReturn();recreated.restore(configuration);yes(recreated.pending());yes(!recreated.completed(code));yes(recreated.completed(second));yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);f.stop();
  f=new F();int third=recreated.prepare(f.intent,ROOM,3);yes(third>second);yes(!recreated.completed(second));yes(StationGameSession.anchorOwner(f.key,ROOM,3)==f.owner);yes(recreated.completed(third));f.stop();
  f=new F();code=recreated.prepare(f.intent,ROOM,3);f.events.send(4,null);Handler.drain();await("leave",5);yes(recreated.completed(code));yes(!recreated.completed(code));yes(StationOnlineClient.count("leave")==5&&StationOnlineClient.count("recovery-failed")==1);f.stop();
  f=new F();code=recreated.prepare(f.intent,ROOM,3);f.events.send(6,null);Handler.drain();await("recovery-failed",2);yes(recreated.completed(code));yes(StationOnlineClient.count("leave")==5&&StationOnlineClient.count("recovery-failed")==2);f.stop();
  f=new F();code=recreated.prepare(f.intent,ROOM,3);recreated.abort(new Intent().putExtra(StationGameSession.ANCHOR_EXTRA,"unrelated"));yes(recreated.pending());yes(StationGameSession.anchorOwner(f.key,ROOM,3)==f.owner);recreated.abort(f.intent);yes(!recreated.pending());yes(StationGameSession.anchorOwner(f.key,ROOM,3)==null);f.stop();
  Field af=StationGameSession.class.getDeclaredField("anchors");af.setAccessible(true);StationSessionRegistry<?> registry=(StationSessionRegistry<?>)af.get(null);int before=registry.size();Intent badIntent=new Intent();badIntent.failExtra=true;boolean failed=false;try{StationGameSession.attach(new Activity(),room(),badIntent);}catch(IllegalArgumentException expected){failed=true;}yes(failed);yes(registry.size()==before);yes(before==0);
  System.out.println("StationSessionLifecycleTest: "+checks+" checks passed; actual Service/Link/GameSession, fake Android scheduler/Binder and HTTP only");
 }
}
