// Only files from the exact owner-specified caratulas directory.
struct SystemVideo720Def {const char* key;const char* asset;};
static const SystemVideo720Def systemVideo720Definitions[]={
{"3ds","turbo-system-videos/720-3ds.mp4"},
{"Playstation 1","turbo-system-videos/720-psx.mp4"},
{"Playstation 2","turbo-system-videos/720-ps2.mp4"},
{"Playstation 2 - BR","turbo-system-videos/720-ps2.mp4"},
{"PSP","turbo-system-videos/720-psp.mp4"},
{"Psvita","turbo-system-videos/720-psvita.mp4"},
{"Switch","turbo-system-videos/720-switch.mp4"},
{"wii","turbo-system-videos/720-wii.mp4"},
{"wiiu","turbo-system-videos/720-wiiu.mp4"},
{"Arcade","turbo-system-videos/720-mame.mp4"},
{"atari2600","turbo-system-videos/720-atari2600.mp4"},
{"Atomiswave","turbo-system-videos/720-atomiswave.mp4"},
{"cps1","turbo-system-videos/720-cps1.mp4"},
{"cps2","turbo-system-videos/720-cps2.mp4"},
{"cps3","turbo-system-videos/720-cps3.mp4"},
{"Dreamcast","turbo-system-videos/720-dreamcast.mp4"},
{"Gba","turbo-system-videos/720-gba.mp4"},
{"mame","turbo-system-videos/720-mame.mp4"},
{"Master System ","turbo-system-videos/720-mastersystem.mp4"},
{"MegaDrive","turbo-system-videos/720-megadrive.mp4"},
{"MegaDrive - BR","turbo-system-videos/720-megadrive.mp4"},
{"model2","turbo-system-videos/720-model2.mp4"},
{"Nintendo 64","turbo-system-videos/720-n64.mp4"},
{"Nintendo 64 - BR","turbo-system-videos/720-n64.mp4"},
{"Nintendo DS","turbo-system-videos/720-nds.mp4"},
{"Neo Geo","turbo-system-videos/720-neogeo.mp4"},
{"Neo Geo CD","turbo-system-videos/720-neogeocd.mp4"},
{"Nintendinho","turbo-system-videos/720-nes.mp4"},
{"sega32x","turbo-system-videos/720-sega32x.mp4"},
{"Super Nintendo","turbo-system-videos/720-snes.mp4"},
{"Super Nintendo - BR","turbo-system-videos/720-snes.mp4"},
{"fbneo","turbo-system-videos/720-fbneo.mp4"},
{"GameCube","turbo-system-videos/720-gc.mp4"},
{"xbox360","turbo-system-videos/720-xbox360.mp4"},
};
