using System.Text.Json;
using TurboRamaSuiteOnlineServer.Online;
long now=1000;int checks=0;
string hash=new('a',64),otherHash=new('b',64);
var engine=new OnlineEngine("test-engine","snes",hash,hash);
var hub=new StationOnline([engine],id=>id=="test-item"?"snes":null,()=>now);
var a=new OnlineIdentity("synthetic-license-A","synthetic-device-A");
var b=new OnlineIdentity("synthetic-license-B","synthetic-device-B");
var c=new OnlineIdentity("synthetic-license-C","synthetic-device-C");
OnlineCommand C(string action)=>new(action,Guid.NewGuid().ToString());
JsonElement J(object value)=>JsonSerializer.SerializeToElement(value,new JsonSerializerOptions(JsonSerializerDefaults.Web));
void Check(bool ok,string name){checks++;if(!ok)throw new Exception(name);}
void F(string code,Action action){try{action();throw new Exception("accepted "+code);}catch(OnlineFailure x){Check(x.Code==code,code);}}
F("STATION_ONLINE_ENTER_REQUIRED",()=>hub.Command(a,C("heartbeat")));
F("STATION_ONLINE_TEXT_INVALID",()=>hub.Command(a,C("enter") with{Nickname="bad\nname"}));
var av=J(hub.Command(a,C("enter") with{Nickname="Jogador A"}));
var bv=J(hub.Command(b,C("enter") with{Nickname="Jogador B"}));
var cv=J(hub.Command(c,C("enter") with{Nickname="Jogador C"}));
Check(cv.GetProperty("totalPeers").GetInt32()==3,"three authenticated peers");
Check(!cv.GetRawText().Contains("synthetic-license"),"license IDs never public");
var create=C("create") with{ItemId="test-item",EngineId="test-engine",ContentSha256=hash,OptionsSha256=hash,CoreSha256=hash,RuntimeSha256=hash};
F("STATION_ONLINE_ITEM_UNAVAILABLE",()=>hub.Command(a,create with{ItemId="missing",RequestId=Guid.NewGuid().ToString()}));
F("STATION_ONLINE_BUILD_MISMATCH",()=>hub.Command(a,create with{CoreSha256=otherHash,RequestId=Guid.NewGuid().ToString()}));
var room=J(hub.Command(a,create)).GetProperty("room");string rid=room.GetProperty("roomId").GetString()!;
Check(room.GetProperty("connectionPassword").GetString()!.Length==64,"private per-room random password");
Check(J(hub.Command(a,create)).GetProperty("room").GetProperty("roomId").GetString()==rid,"create idempotent");
F("STATION_ONLINE_REQUEST_REUSED",()=>hub.Command(a,create with{ItemId="another"}));
Check(!J(hub.Command(c,C("heartbeat"))).GetRawText().Contains("connectionPassword"),"outsider receives no connection secret");
hub.Command(a,C("invite") with{RoomId=rid,PeerId=bv.GetProperty("selfId").GetString()});
Check(J(hub.Command(b,C("heartbeat"))).GetProperty("invites").GetArrayLength()==1,"invitation delivered");
F("STATION_ONLINE_ROOM_NOT_FOUND",()=>hub.Command(c,C("chat") with{RoomId=rid,Text="outsider"}));
var join=C("join") with{RoomId=rid,ContentSha256=hash,OptionsSha256=hash,CoreSha256=hash,RuntimeSha256=hash};
F("STATION_ONLINE_BUILD_MISMATCH",()=>hub.Command(b,join with{ContentSha256=otherHash,RequestId=Guid.NewGuid().ToString()}));
hub.Command(b,join);
F("STATION_ONLINE_ROOM_FULL",()=>hub.Command(c,join with{RequestId=Guid.NewGuid().ToString()}));
F("STATION_ONLINE_NOT_READY",()=>hub.Command(a,C("start") with{RoomId=rid,Address="192.168.1.10",Port=55435}));
var before=J(hub.Command(a,C("heartbeat")));
var poll=hub.Events(a,before.GetProperty("instance").GetString(),before.GetProperty("revision").GetInt64(),0,CancellationToken.None);
Check(!poll.IsCompleted,"events wait without repeated polling");
var message=C("chat") with{RoomId=rid,Text="Vamos jogar!"};hub.Command(b,message);
var updated=J(await poll.WaitAsync(TimeSpan.FromSeconds(1)));
Check(updated.GetProperty("room").GetProperty("messages").GetArrayLength()==1,"chat wakes events immediately");
hub.Command(b,message);
Check(J(hub.Command(a,C("heartbeat"))).GetProperty("room").GetProperty("messages").GetArrayLength()==1,"chat retry has no duplicate");
F("STATION_ONLINE_CHAT_LIMIT",()=>hub.Command(b,C("chat") with{RoomId=rid,Text="flood"}));
hub.Command(a,C("ready") with{RoomId=rid,Value=true});hub.Command(b,C("ready") with{RoomId=rid,Value=true});
F("STATION_ONLINE_HOST_REQUIRED",()=>hub.Command(b,C("start") with{RoomId=rid,Address="192.168.1.10",Port=55435}));
F("STATION_ONLINE_ENDPOINT_INVALID",()=>hub.Command(a,C("start") with{RoomId=rid,Address="127.0.0.1",Port=55435}));
F("STATION_ONLINE_ENDPOINT_INVALID",()=>hub.Command(a,C("start") with{RoomId=rid,Address="224.0.0.1",Port=55435}));
var started=J(hub.Command(a,C("start") with{RoomId=rid,Address="192.168.1.10",Port=55435}));
Check(started.GetProperty("room").GetProperty("state").GetString()=="starting","guest waits for actual native host listening");
F("STATION_ONLINE_HOST_REQUIRED",()=>hub.Command(b,C("host-listening") with{RoomId=rid}));
var listening=J(hub.Command(a,C("host-listening") with{RoomId=rid}));
Check(listening.GetProperty("room").GetProperty("state").GetString()=="connecting","host listening signal releases guest but does not claim game synchronized");
hub.Command(b,C("leave"));
Check(J(hub.Command(a,C("heartbeat"))).GetProperty("room").ValueKind==JsonValueKind.Null,"leaving match closes session for host");
Check(J(hub.Command(a,create)).GetProperty("room").ValueKind==JsonValueKind.Null,"old retry cannot resurrect a departed room or expose its secret");
now+=11000;
var second=J(hub.Command(a,create with{RequestId=Guid.NewGuid().ToString()})).GetProperty("room");
rid=second.GetProperty("roomId").GetString()!;
hub.Command(b,C("block") with{PeerId=av.GetProperty("selfId").GetString()});
F("STATION_ONLINE_BLOCKED",()=>hub.Command(b,join with{RoomId=rid,RequestId=Guid.NewGuid().ToString()}));
F("STATION_ONLINE_BLOCKED",()=>hub.Command(a,C("invite") with{RoomId=rid,PeerId=bv.GetProperty("selfId").GetString()}));
hub.Revoke(a);
Check(J(hub.Command(c,C("heartbeat"))).GetProperty("rooms").GetArrayLength()==0,"revocation removes host rooms");
now+=60001;
F("STATION_ONLINE_ENTER_REQUIRED",()=>hub.Command(b,C("heartbeat")));
var fresh=J(hub.Command(a,C("enter") with{Nickname="Fresh"}));
Check(fresh.GetProperty("totalPeers").GetInt32()==1,"offline peers expire without fake online entries");
var renamed=J(hub.Command(a,C("enter") with{Nickname="New name"}));
Check(renamed.GetProperty("peers")[0].GetProperty("nickname").GetString()=="New name","foreground presence allows nickname update in rooms");
F("STATION_ONLINE_PAGE_INVALID",()=>hub.Events(a,"old",0,99,CancellationToken.None).GetAwaiter().GetResult());
var sample=J(hub.Command(a,C("heartbeat")));using var cancel=new CancellationTokenSource();
var waiting=hub.Events(a,sample.GetProperty("instance").GetString(),sample.GetProperty("revision").GetInt64(),0,cancel.Token);cancel.Cancel();
try{await waiting;throw new Exception("cancellation ignored");}catch(OperationCanceledException){checks++;}
var offline=C("offline");hub.Command(a,offline);Check(J(hub.Command(a,offline)).GetProperty("offline").GetBoolean(),"offline retry idempotent");
// Independent clock and hub cover a host which never opens its native listening socket.
var timed=new StationOnline([engine],id=>"snes",()=>now);
timed.Command(a,C("enter") with{Nickname="A"});timed.Command(b,C("enter") with{Nickname="B"});
string timeoutRoom=J(timed.Command(a,create with{RequestId=Guid.NewGuid().ToString()})).GetProperty("room").GetProperty("roomId").GetString()!;
timed.Command(b,join with{RoomId=timeoutRoom,RequestId=Guid.NewGuid().ToString()});
timed.Command(a,C("ready") with{RoomId=timeoutRoom,Value=true});timed.Command(b,C("ready") with{RoomId=timeoutRoom,Value=true});
timed.Command(a,C("start") with{RoomId=timeoutRoom,Address="192.168.1.10",Port=55435});
now+=30001;
Check(J(timed.Command(a,C("heartbeat"))).GetProperty("room").ValueKind==JsonValueKind.Null,"failed native host closes starting room after timeout");
Check(J(timed.Command(b,C("heartbeat") with{Page=1})).GetProperty("page").GetInt32()==1,"page selection uses command, not a second concurrent event poll");
F("STATION_ONLINE_PAGE_INVALID",()=>timed.Command(a,C("heartbeat") with{Page=41}));
Console.WriteLine(JsonSerializer.Serialize(new{passed=true,checks,scope="Synthetic in-process room and chat tests; no production service or Android game used"}));
