.section .rodata
.balign 4
.global station_lottie_switch_rle
station_lottie_switch_rle:
.incbin "E:/ESTUDO APK/work/station-theme-collections-r39-20261006/data/lottie/switch.rle"
.balign 4
.global station_lottie_stars_rle
station_lottie_stars_rle:
.incbin "E:/ESTUDO APK/work/station-theme-collections-r39-20261006/data/lottie/stars.rle"
.balign 4
.global station_lottie_chatbot_rle
station_lottie_chatbot_rle:
.incbin "E:/ESTUDO APK/work/station-theme-collections-r39-20261006/data/lottie/chatbot.rle"
.balign 4
.global station_lottie_online_rle
station_lottie_online_rle:
.incbin "E:/ESTUDO APK/work/station-theme-collections-r39-20261006/data/lottie/online.rle"
